### ISSUE TITLE
[FIX] 웹팩 

### ISSUE THREAD

**Issue by yoon-junseo** [yoon-junseo/template#8]
## 설명
- 웹팩 설정 변경

## ToDo
- [x] 웹팩의 EnvironmentPlugin 수정
- [x] style-loader 추가
- [x] 사진 모듈에 webp 추가
